/* Public reference metadata. Administrative example records are generated locally. */
export const CINEMATCH_DATA = {
  catalog: [
    {
      id: "downsday-2026",
      name: "Vingadores Doownsday",
      type: "movie",
      image: "assets/cartazes/filmes/app-movie-doownsday.jpg",
      trailer: "https://www.youtube.com/watch?v=ntOtyJwxcsM",
      rating: "10",
      language: "English",
      duration: "02:45",
      release: "2026-09-26",
      genres: ["Action", "Comedy"],
      access: "pay-per-view",
      status: true,
      description: "Vingadores: Doutor Destino é a primeira sequência de Vingadores na fase Multiverso e faz parte da fase 6 do Universo Cinematográfico Marvel. O quinto longa-metragem dos Vingadores, dirigido pelos irmãos Russo, ainda não possui uma sinopse oficial, mas foi revelado que Robert Downey Jr. irá interpretar o vilão Doutor Destino.",
      video: "",
    },
    {
      id: "lanternas",
      name: "LANTERNAS",
      type: "movie",
      image: "assets/cartazes/filmes/app-movie-lanternas.jpg",
      trailer: "https://www.youtube.com/watch?v=ngEWGqu66jI",
      rating: "9.8",
      language: "English",
      duration: "02:35",
      release: "2026-08-26",
      genres: ["Action", "Historical"],
      access: "pay-per-view",
      status: true,
      description: "Lanternas é a nova série focada no universo da DC e irá acompanhar as aventuras do Lanterna Verde, super-herói que, com a ajuda de um poderoso anel, consegue criar objetos plasmados complexos usando apenas a força da sua mente. Agora, Hal Jordan (Kyle Chandler) terá um novo recruta, o John Stewart (Aaron Pierre), e juntos, enquanto policiais intergalácticos, eles terão que sobreviver ao lado sombrio e misterioso da Terra ao mesmo tempo em que investigam um assassinato no coração dos Estados Unidos.",
      video: "",
    },
    
    {
      id: "the-house-of-last-respite",
      name: "The House of Last Respite",
      type: "movie",
      image: "assets/cartazes/filmes/the_house_of_last_respite_poster.png",
      trailer: "https://youtu.be/WaewToFT59c?si=204R6vnVc3NfrrN5",
      rating: "6",
      language: "English",
      duration: "02:35",
      release: "2025-07-08",
      genres: ["Horror", "Comedy"],
      access: "pay-per-view",
      status: true,
      description: "",
      video: "",
    },
    {
      id: "legends-of-the-eternal-flame",
      name: "Legends of the Eternal Flame",
      type: "movie",
      image: "assets/cartazes/filmes/legends_of_the_eternal_flame_poster.png",
      trailer: "https://youtu.be/nzzq4V2I6hE?si=wkokzDNAvvxLY9Tm",
      rating: "6",
      language: "English",
      duration: "02:45",
      release: "2025-07-06",
      genres: ["Animation", "Historical", "Horror"],
      access: "pay-per-view",
      status: true,
      description: "",
      video: "",
    },
    {
      id: "wolves-of-the-dawn",
      name: "Wolves of the Dawn",
      type: "movie",
      image: "assets/cartazes/filmes/wolves_of_the_dawn_poster.png",
      trailer: "https://youtu.be/MAFsRmx6pPo?si=CJjoeRbHVtKJt9oC",
      rating: "6",
      language: "English",
      duration: "02:56",
      release: "2025-07-04",
      genres: ["Historical", "Action", "Horror"],
      access: "pay-per-view",
      status: true,
      description: "",
      video: "",
    },
    {
      id: "warriors-of-the-eternal-realm",
      name: "Warriors of the Eternal Realm",
      type: "movie",
      image: "assets/cartazes/filmes/warriors_of_the_eternal_realm_poster.png",
      trailer: "https://youtu.be/7VXOHmaTd7g?si=Qjm-q92VPXnVG5NN",
      rating: "6",
      language: "English",
      duration: "02:40",
      release: "2025-06-22",
      genres: ["Historical", "Action", "Inspirational"],
      access: "pay-per-view",
      status: true,
      description: "",
      video: "",
    },
    {
      id: "vengeance-in-the-wild",
      name: "Vengeance in the Wild",
      type: "movie",
      image: "assets/cartazes/filmes/vengeance_in_the_wild_poster.png",
      trailer: "https://youtu.be/EbrTRE96wS0?si=GVHICrYbbCTkGA35",
      rating: "8.5",
      language: "English",
      duration: "02:45",
      release: "2025-06-10",
      genres: ["Thriller", "Action", "Animation"],
      access: "pay-per-view",
      status: true,
      description: "",
      video: "",
    },
    {
      id: "texting-for-love",
      name: "Texting for Love",
      type: "movie",
      image: "assets/cartazes/filmes/texting_for_love_poster.png",
      trailer: "https://youtu.be/CQDXtD2HJAs?si=p9loI6UOGTOniMbO",
      rating: "8.5",
      language: "English",
      duration: "03:00",
      release: "2025-06-06",
      genres: ["Romantic", "Inspirational", "Horror"],
      access: "pay-per-view",
      status: true,
      description: "",
      video: "",
    },
    {
      id: "gramps-and-the-grandkid-circus",
      name: "Gramps and the Grandkid Circus",
      type: "movie",
      image: "assets/cartazes/filmes/gramps_and_the_grandkid_circus_poster.png",
      trailer: "https://youtu.be/mJ_Tex6KT6w?si=0bhjIh5zYTZlk9EU",
      rating: "8.5",
      language: "English",
      duration: "02:30",
      release: "2025-06-05",
      genres: ["Comedy", "Historical", "Romantic"],
      access: "pay-per-view",
      status: true,
      description: "",
      video: "",
    },
    {
      id: "fang-of-the-steppe",
      name: "Fang of the Steppe",
      type: "movie",
      image: "assets/cartazes/filmes/fang_of_the_steppe_poster.png",
      trailer: "https://youtu.be/PI4Z7t3AZ5E?si=QNKYohZ1ZgLol_OP",
      rating: "8.5",
      language: "English",
      duration: "01:50",
      release: "2025-05-11",
      genres: ["Horror", "Inspirational", "Romantic"],
      access: "pay-per-view",
      status: true,
      description: "",
      video: "",
    },
    {
      id: "ultimate-kitchen-organization-hacks",
      name: "Ultimate Kitchen Organization Hacks",
      type: "video",
      image: "assets/cartazes/videos/ultimate_kitchen_organization_hacks.png",
      trailer: null,
      rating: null,
      language: "English",
      duration: "00:45",
      release: "",
      genres: [],
      access: "free",
      status: true,
      description: "",
      video: "",
    },
    {
      id: "catcalls-the-haunting",
      name: "Catcalls: The Haunting",
      type: "video",
      image: "assets/cartazes/videos/catcalls_the_haunting.png",
      trailer: null,
      rating: null,
      language: "English",
      duration: "00:50",
      release: "",
      genres: [],
      access: "free",
      status: true,
      description: "",
      video: "",
    },
    {
      id: "dead-zone-heist",
      name: "Dead Zone Heist",
      type: "movie",
      image: "assets/cartazes/filmes/dead_zone_heist_poster.png",
      trailer: "https://youtu.be/HHJkUQGm2H8?si=azs9wdvXt22o54B3",
      rating: "6",
      language: "English",
      duration: "02:40",
      release: "2025-08-23",
      genres: ["Animation", "Romantic", "Thriller"],
      access: "paid",
      status: true,
      description: "",
      video: "",
    },
    {
      id: "beneath-the-surface",
      name: "Beneath the Surface",
      type: "movie",
      image: "assets/cartazes/filmes/beneath_the_surface_poster.png",
      trailer: "https://youtu.be/l3P2vrcKiXs?si=PG6Yj6Bff7KrDaeB",
      rating: "6",
      language: "English",
      duration: "02:58",
      release: "2025-08-10",
      genres: ["Romantic", "Historical", "Comedy"],
      access: "free",
      status: true,
      description: "",
      video: "",
    },
    {
      id: "family-feud-fiasco",
      name: "Family Feud Fiasco",
      type: "movie",
      image: "assets/cartazes/filmes/family_feud_fiasco_poster.png",
      trailer: "https://youtu.be/0Ji6i79LiL8?si=IIG3-D6Jl72oJq0_",
      rating: "6",
      language: "English",
      duration: "01:30",
      release: "2025-07-18",
      genres: ["Action", "Comedy"],
      access: "free",
      status: true,
      description: "",
      video: "",
    },
    {
      id: "the-charlie-game-shadows-unleashed",
      name: "The Charlie Game: Shadows Unleashed",
      type: "movie",
      image:
        "assets/cartazes/filmes/the_charlie_game_shadows_unleashed_poster.png",
      trailer: "https://youtu.be/mIaKS3OtqEg?si=-qrD6nVQxrTGsSm-",
      rating: "6",
      language: "English",
      duration: "01:50",
      release: "2025-06-21",
      genres: ["Horror", "Comedy", "Animation"],
      access: "free",
      status: true,
      description: "",
      video: "",
    },
    {
      id: "forsaken-battalion",
      name: "Forsaken Battalion",
      type: "movie",
      image: "assets/cartazes/filmes/forsaken_battalion_poster.png",
      trailer: "https://youtu.be/aDyQxtg0V2w?si=ydtmf91vHvNuvVMX",
      rating: "6",
      language: "English",
      duration: "02:55",
      release: "2025-06-20",
      genres: ["Action", "Inspirational", "Romantic"],
      access: "paid",
      status: true,
      description: "",
      video: "",
    },
    {
      id: "broken-sanctuary",
      name: "Broken Sanctuary",
      type: "movie",
      image: "assets/cartazes/filmes/broken_sanctuary_poster.png",
      trailer: "https://youtu.be/Mtah8SplQCA?si=4DqJPL6641jUR03m",
      rating: "8.6",
      language: "English",
      duration: "02:30",
      release: "2025-05-06",
      genres: ["Thriller", "Inspirational", "Horror"],
      access: "paid",
      status: true,
      description: "",
      video: "",
    },
    {
      id: "modern-family",
      name: "Modern Family",
      type: "tvshow",
      image: "assets/cartazes/series/app-show-family.jpg",
      trailer: "https://youtu.be/bvDArsKoTOE?si=2wx6GVga2c-afd7y",
      rating: "8",
      language: "English",
      duration: null,
      release: "2025-08-25",
      genres: ["Thriller", "Action", "Animation", "Historical"],
      access: "paid",
      status: true,
      description: "",
      video: "",
    },
    {
      id: "game-of-thrones",
      name: "Game of Thrones",
      type: "tvshow",
      image: "assets/cartazes/series/app-show-game.jpg",
      trailer: "https://youtu.be/AW0A_VE245c?si=msNsH9EnTnvesnDH",
      rating: "4",
      language: "English",
      duration: null,
      release: "2025-05-02",
      genres: ["Inspirational", "Action", "Romantic"],
      access: "free",
      status: true,
      description: "",
      video: "",
    },
    {
      id: "journey-to-the-core",
      name: "Journey to the Core",
      type: "tvshow",
      image: "assets/cartazes/series/journey_to_the_core_poster.png",
      trailer: "https://youtu.be/XI8uxmTSBWo?si=U5qJDxWja_3l4Vp9",
      rating: "9",
      language: "English",
      duration: null,
      release: "2025-04-13",
      genres: ["Action", "Comedy", "Horror"],
      access: "paid",
      status: true,
      description: "",
      video: "",
    },
    {
      id: "valiant-horizons",
      name: "Valiant Horizons",
      type: "tvshow",
      image: "assets/cartazes/series/valiant_horizons_poster.png",
      trailer: "https://youtu.be/aDyQxtg0V2w?si=ydtmf91vHvNuvVMX",
      rating: "6",
      language: "English",
      duration: null,
      release: "2025-03-01",
      genres: ["Historical", "Thriller", "Romantic", "Inspirational"],
      access: "paid",
      status: true,
      description: "",
      video: "",
    },
    {
      id: "legacy-of-the-tribes",
      name: "Legacy of the Tribes",
      type: "tvshow",
      image: "assets/cartazes/series/legacy_of_the_tribes_poster.png",
      trailer: "https://youtu.be/GKq7QlNz3CA?si=E6fnSD4CvpEPcMu7",
      rating: "9",
      language: "English",
      duration: null,
      release: "2025-02-20",
      genres: ["Animation", "Romantic", "Thriller"],
      access: "free",
      status: true,
      description: "",
      video: "",
    },
    {
      id: "wolfbound",
      name: "Wolfbound",
      type: "tvshow",
      image: "assets/cartazes/series/wolfbound_poster.png",
      trailer: "https://youtu.be/6sxnOLRGkhw?si=WrBfEDVah3Z-vFwO",
      rating: "8",
      language: "English",
      duration: "08:50",
      release: "2025-02-16",
      genres: ["Animation", "Action", "Comedy"],
      access: "free",
      status: true,
      description: "",
      video: "",
    },
    {
      id: "the-hidden-truth",
      name: "The Hidden Truth",
      type: "tvshow",
      image: "assets/cartazes/series/the_hidden_truth_poster.png",
      trailer: "https://youtu.be/em1ec7BZHJw?si=MSD31eT22XrZ7ohu",
      rating: "8.1",
      language: "English",
      duration: "09:50",
      release: "2025-01-11",
      genres: ["Thriller", "Romantic", "Inspirational"],
      access: "free",
      status: true,
      description: "",
      video: "",
    },
    {
      id: "shadow-pursuit",
      name: "Shadow Pursuit",
      type: "tvshow",
      image: "assets/cartazes/series/shadow_pursuit_poster.png",
      trailer: "https://youtu.be/T5UokLYVJMI?si=7DVFmcXSmf5zVGKj",
      rating: "8.2",
      language: "English",
      duration: "05:50",
      release: "2022-08-05",
      genres: ["Thriller", "Inspirational", "Historical"],
      access: "paid",
      status: true,
      description: "",
      video: "",
    },
    {
      id: "the-smiling-doll",
      name: "The Smiling doll",
      type: "tvshow",
      image: "assets/cartazes/series/app-home.jpg",
      trailer: "https://youtu.be/7_MJp5AbSwA?si=Mtx9h0wlxtn4o_2Q",
      rating: "7.5",
      language: "English",
      duration: "05:20",
      release: "2019-04-23",
      genres: ["Horror", "Action", "Comedy"],
      access: "free",
      status: true,
      description: "",
      video: "",
    },
    {
      id: "operation-viper",
      name: "Operation Viper",
      type: "movie",
      image: "assets/cartazes/filmes/operation_viper_poster.png",
      trailer: "https://youtu.be/5zSPGLoN9lQ?si=vIAtP5OnEQ4gnMV8",
      rating: "6.2",
      language: "English",
      duration: "03:00",
      release: "2010-04-23",
      genres: ["Action", "Animation", "Comedy"],
      access: "free",
      status: true,
      description: "",
      video: "",
    },
    {
      id: "the-gunfighters-redemption",
      name: "The Gunfighter's Redemption",
      type: "movie",
      image: "assets/cartazes/filmes/the_gunfighters_redemption_poster.png",
      trailer: "https://youtu.be/ob8iKn-gLFI?si=sUpU_bMpIDocTFZ6",
      rating: "8.2",
      language: "English",
      duration: "02:30",
      release: "2012-03-08",
      genres: ["Action", "Horror", "Inspirational"],
      access: "free",
      status: true,
      description: "",
      video: "",
    },
    {
      id: "daizys-enchanted-journey",
      name: "Daizy's Enchanted Journey",
      type: "movie",
      image: "assets/cartazes/filmes/daizys_enchanted_journey_poster.png",
      trailer: "https://youtu.be/1c3O3-sVFC0?si=p7TI-JkU7E5LB5HJ",
      rating: "7.1",
      language: "English",
      duration: "03:06",
      release: "2014-07-06",
      genres: ["Animation", "Historical", "Horror"],
      access: "free",
      status: true,
      description: "",
      video: "",
    },
    {
      id: "luca",
      name: "Luca",
      type: "movie",
      image: "assets/cartazes/filmes/app-movie-luca.jpg",
      trailer: "https://youtu.be/gxslnpqFwOs?si=fRi0Wnbd4qUCw43i",
      rating: "7.5",
      language: "English",
      duration: "02:15",
      release: "2016-06-04",
      genres: ["Animation", "Thriller", "Science Fiction"],
      access: "free",
      status: true,
      description: "",
      video: "",
    },
    {
      id: "the-adam-project",
      name: "The Adam Project",
      type: "movie",
      image: "assets/cartazes/filmes/app-movies-project.jpg",
      trailer: "https://youtu.be/Mmq_NVwLN_g?si=JfALgqlfHlZgaoZP",
      rating: "8.1",
      language: "English",
      duration: "02:40",
      release: "2026-09-20",
      genres: ["Comedy", "Romantic", "Horror"],
      access: "free",
      status: true,
      description: "",
      video: "",
    },
    {
      id: "the-night-owl",
      name: "The Night Owl",
      type: "movie",
      image: "assets/cartazes/filmes/app-movie-owl.jpg",
      trailer: "https://youtu.be/fEzWvEoD9ew?si=YNoDNhX0EOQ4oXsH",
      rating: "9",
      language: "English",
      duration: "02:35",
      release: "2020-04-04",
      genres: ["Comedy", "Romantic", "Horror"],
      access: "free",
      status: true,
      description: "",
      video: "",
    },
    {
      id: "frank-and-fearless-adventures",
      name: "Frank and Fearless Adventures",
      type: "movie",
      image: "assets/cartazes/filmes/frank_and_fearless_adventures_poster.png",
      trailer: "https://youtu.be/_8slPqV-16w?si=oCMjQ4pRqCEBc-fF",
      rating: "8.7",
      language: "English",
      duration: "02:58",
      release: "2020-06-11",
      genres: ["Comedy", "Historical", "Animation"],
      access: "free",
      status: true,
      description: "",
      video: "",
    },
    {
      id: "echoes-of-terror",
      name: "Echoes of Terror",
      type: "movie",
      image: "assets/cartazes/filmes/echoes_of_terror_poster.png",
      trailer: "https://youtu.be/smTK_AeAPHs?si=UQAlhFHgP-j1YSjG",
      rating: "7.5",
      language: "English",
      duration: "02:50",
      release: "2021-07-08",
      genres: ["Horror", "Thriller", "Romantic"],
      access: "free",
      status: true,
      description: "",
      video: "",
    },
    {
      id: "haunting-shadows",
      name: "Haunting Shadows",
      type: "movie",
      image: "assets/cartazes/filmes/haunting_shadows_poster.png",
      trailer: "https://youtu.be/_XV764KWBrA?si=dX3daijNvpduGGKR",
      rating: "8.2",
      language: "English",
      duration: "02:40",
      release: "2020-07-03",
      genres: ["Horror", "Historical", "Animation"],
      access: "free",
      status: true,
      description: "",
      video: "",
    },
    {
      id: "origins-of-civilization-the-dawn-of-empires",
      name: "Origins of Civilization: The Dawn of Empires",
      type: "movie",
      image: "assets/cartazes/filmes/origins_civilization_poster.png",
      trailer: "https://youtu.be/W0_55mECsa4?si=b_AlIpdvNC_wZ5Zr",
      rating: "8.5",
      language: "English",
      duration: "02:56",
      release: "2026-09-18",
      genres: ["Historical", "Inspirational", "Thriller"],
      access: "free",
      status: true,
      description: "",
      video: "",
    },
    {
      id: "midnight-thrills",
      name: "Midnight Thrills",
      type: "video",
      image: "assets/cartazes/videos/midnight_thrills.png",
      trailer: null,
      rating: null,
      language: "English",
      duration: "00:45",
      release: "",
      genres: [],
      access: "free",
      status: true,
      description: "",
      video: "",
    },
    {
      id: "hearts-entwined",
      name: "Hearts Entwined",
      type: "video",
      image: "assets/cartazes/videos/hearts_entwined.png",
      trailer: null,
      rating: null,
      language: "English",
      duration: "01:20",
      release: "",
      genres: [],
      access: "free",
      status: true,
      description: "",
      video: "",
    },
    {
      id: "gnomeos-love-stories",
      name: "Gnomeo's Love Stories",
      type: "video",
      image: "assets/cartazes/videos/gnomeos_love_stories.png",
      trailer: null,
      rating: null,
      language: "English",
      duration: "00:50",
      release: "",
      genres: [],
      access: "free",
      status: true,
      description: "",
      video: "",
    },
    {
      id: "school-hacks-fun-diy-crafts",
      name: "School Hacks & Fun DIY Crafts",
      type: "video",
      image: "assets/cartazes/videos/school_hacks_fun_diy_crafts.png",
      trailer: null,
      rating: null,
      language: "English",
      duration: "00:50",
      release: "",
      genres: [],
      access: "free",
      status: true,
      description: "",
      video: "",
    },
    {
      id: "big-style-on-a-small-budget",
      name: "Big Style on a Small Budget",
      type: "video",
      image: "assets/cartazes/videos/big_style_on_a_small_budget.png",
      trailer: null,
      rating: null,
      language: "English",
      duration: "00:20",
      release: "",
      genres: [],
      access: "free",
      status: true,
      description: "",
      video: "",
    },
    {
      id: "life-changing-fitness-habits-daily-healthy-tips",
      name: "Life Changing Fitness Habits - Daily Healthy Tips",
      type: "video",
      image:
        "assets/cartazes/videos/life_changing_fitness_habits_daily_healthy_tips.png",
      trailer: null,
      rating: null,
      language: "English",
      duration: "00:45",
      release: "",
      genres: [],
      access: "free",
      status: true,
      description: "",
      video: "",
    },
    {
      id: "potato-perfection",
      name: "Potato Perfection",
      type: "video",
      image: "assets/cartazes/videos/potato_perfection.png",
      trailer: null,
      rating: null,
      language: "English",
      duration: "00:20",
      release: "",
      genres: [],
      access: "free",
      status: true,
      description: "",
      video: "",
    },
    {
      id: "creative-3d-pen-crafts",
      name: "Creative 3D Pen Crafts",
      type: "video",
      image: "assets/cartazes/videos/creative_3d_pen_crafts.png",
      trailer: null,
      rating: null,
      language: "English",
      duration: "00:45",
      release: "",
      genres: [],
      access: "free",
      status: true,
      description: "",
      video: "",
    },
    {
      id: "food-prep-mastery",
      name: "Food Prep Mastery",
      type: "video",
      image: "assets/cartazes/videos/food_prep_mastery.png",
      trailer: null,
      rating: null,
      language: "English",
      duration: "00:45",
      release: "",
      genres: [],
      access: "free",
      status: true,
      description: "",
      video: "",
    },
    {
      id: "major-1",
      name: "Major 1",
      type: "movie",
      image: "assets/cartazes/filmes/i7UyjfPio0VFHB9rBUZSFyhOoM8.jpg",
      trailer:
        "https://vz-56319c06-a78.b-cdn.net/48b28565-151f-4598-bedf-2540ceeff925/playlist.m3u8",
      rating: null,
      language: "Spanish",
      duration: "01:35",
      release: "2026-09-16",
      genres: ["Adventure", "Horror", "Science Fiction"],
      access: "free",
      status: true,
      description: "",
      video: "",
    },
    {
      id: "prueba",
      name: "Prueba",
      type: "movie",
      image: "assets/cartazes/filmes/rogue_redemption_poster.png",
      trailer: "https://www.youtube.com/watch?v=1r-PlKRYe7c",
      rating: null,
      language: "English",
      duration: "01:40",
      release: "2026-04-14",
      genres: ["Action"],
      access: "free",
      status: true,
      description: "",
      video: "",
    },
    {
      id: "the-cursed-frontier",
      name: "The Cursed Frontier",
      type: "movie",
      image: "assets/cartazes/filmes/the_cursed_frontier_poster.png",
      trailer: "https://youtu.be/6sxnOLRGkhw?si=WrBfEDVah3Z-vFwO",
      rating: "6",
      language: "English",
      duration: "02:45",
      release: "2025-08-27",
      genres: ["Action", "Romantic", "Thriller"],
      access: "free",
      status: true,
      description: "",
      video: "",
    },
    {
      id: "the-haunting-veil",
      name: "The Haunting Veil",
      type: "movie",
      image: "assets/cartazes/filmes/the_haunting_veil_poster.png",
      trailer: "https://youtu.be/BruiisujNJY?si=GGnUUVXqX0BfCTQC",
      rating: "6",
      language: "English",
      duration: "02:56",
      release: "2025-08-20",
      genres: ["Comedy", "Historical", "Horror"],
      access: "free",
      status: true,
      description: "",
      video: "",
    },
    {
      id: "nowhere-to-hide",
      name: "Nowhere to Hide",
      type: "movie",
      image: "assets/cartazes/filmes/nowhere_to_hide_poster.png",
      trailer: "https://youtu.be/7EzpvriIQ3I?si=32wWLtYpLoOf7QuP",
      rating: "6",
      language: "English",
      duration: "02:50",
      release: "2025-08-17",
      genres: ["Thriller", "Inspirational", "Horror"],
      access: "free",
      status: true,
      description: "",
      video: "",
    },
    {
      id: "faithful-survival",
      name: "Faithful Survival",
      type: "movie",
      image: "assets/cartazes/filmes/faithful_survival_poster.png",
      trailer: "https://youtu.be/QKjZSOjzChg?si=_GIkyvBk5D53D9nJ",
      rating: "6",
      language: "English",
      duration: "02:35",
      release: "2025-08-07",
      genres: ["Inspirational", "Animation", "Comedy"],
      access: "free",
      status: true,
      description: "",
      video: "",
    },
    {
      id: "crossroads-of-conflict",
      name: "Crossroads of Conflict",
      type: "movie",
      image: "assets/cartazes/filmes/crossroads_of_conflict_poster.png",
      trailer: "https://youtu.be/s2-1hz1juBI?si=OG5eOFO6QnSfLiFb",
      rating: "6",
      language: "English",
      duration: "02:40",
      release: "2025-08-06",
      genres: ["Historical", "Horror", "Romantic"],
      access: "paid",
      status: true,
      description: "",
      video: "",
    },
    {
      id: "cultural-clash-comedy",
      name: "Cultural Clash Comedy",
      type: "movie",
      image: "assets/cartazes/filmes/cultural_clash_comedy_poster.png",
      trailer: "https://youtu.be/pCMHc-IFAB0?si=vIVQzT73CoPjbEio",
      rating: "6",
      language: "English",
      duration: "01:50",
      release: "2025-08-03",
      genres: ["Comedy", "Historical", "Horror"],
      access: "paid",
      status: true,
      description: "",
      video: "",
    },
    {
      id: "charlottes-curse",
      name: "Charlotte's Curse",
      type: "movie",
      image: "assets/cartazes/filmes/charlottes_curse_poster.png",
      trailer: "https://youtu.be/TY6X-vXSZjU?si=avF0vLQtTLiOzjRb",
      rating: "6",
      language: "English",
      duration: "02:55",
      release: "2025-08-01",
      genres: ["Horror", "Animation", "Comedy"],
      access: "free",
      status: true,
      description: "",
      video: "",
    },
    {
      id: "hearts-of-valor",
      name: "Hearts of Valor",
      type: "movie",
      image: "assets/cartazes/filmes/hearts_of_valor_poster.png",
      trailer: "https://vidsrc.sbs/embed/movie/11178",
      rating: "6",
      language: "English",
      duration: "02:50",
      release: "2025-07-31",
      genres: ["Animation", "Horror", "Thriller"],
      access: "free",
      status: true,
      description: "",
      video: "",
    },
    {
      id: "fear-factor",
      name: "Fear Factor",
      type: "tvshow",
      image: "assets/cartazes/series/app-show-factor.jpg",
      trailer: "https://youtu.be/O9i2vmFhSSY?si=YYmzH5_dw63-BeNU",
      rating: "5",
      language: "English",
      duration: null,
      release: "2025-10-16",
      genres: ["Thriller", "Inspirational", "Horror"],
      access: "free",
      status: true,
      description: "",
      video: "",
    },
    {
      id: "evil-awakening",
      name: "Evil Awakening",
      type: "tvshow",
      image: "assets/cartazes/series/evil_awakening_poster.png",
      trailer: "https://youtu.be/6LiKKFZyhRU?si=1al4KGEcQdP3LTQ1",
      rating: "4",
      language: "English",
      duration: null,
      release: "2025-09-26",
      genres: ["Horror", "Inspirational", "Thriller", "Action"],
      access: "free",
      status: true,
      description: "",
      video: "",
    },
    {
      id: "heritage-hijinks",
      name: "Heritage Hijinks",
      type: "tvshow",
      image: "assets/cartazes/series/heritage_hijinks_poster.png",
      trailer: "https://youtu.be/WXpBN_31-Cw?si=xg1UJ2J5chVUWHdY",
      rating: "7",
      language: "English",
      duration: null,
      release: "2025-09-05",
      genres: ["Comedy", "Horror", "Romantic", "Inspirational"],
      access: "free",
      status: true,
      description: "",
      video: "",
    },
    {
      id: "house-of-the-dragon",
      name: "House of the Dragon",
      type: "tvshow",
      image: "assets/cartazes/series/app-show-dragon.jpg",
      trailer: "https://youtu.be/rS15OQLyWIs?si=9TIyww8T6LJCFSrr",
      rating: "4",
      language: "English",
      duration: null,
      release: "2025-07-10",
      genres: ["Romantic", "Horror", "Inspirational", "Thriller"],
      access: "paid",
      status: true,
      description: "",
      video: "",
    },
    {
      id: "mcdoll-mayhem",
      name: "McDoll Mayhem",
      type: "tvshow",
      image: "assets/cartazes/series/mcdoll_mayhem_poster.png",
      trailer: "https://youtu.be/skl7gYRZHwE?si=kiekCHcihmEJH54D",
      rating: "5",
      language: "English",
      duration: null,
      release: "2025-06-21",
      genres: ["Comedy", "Horror", "Romantic"],
      access: "free",
      status: true,
      description: "",
      video: "",
    },
    {
      id: "snip-spy-the-cutthroat-mission",
      name: "Snip & Spy: The Cutthroat Mission",
      type: "tvshow",
      image: "assets/cartazes/series/snip_spy_the_cutthroat_mission_poster.png",
      trailer: "https://youtu.be/eH7EyPs_Va8?si=BRcgB15dMbdoEj7G",
      rating: "3",
      language: "English",
      duration: null,
      release: "2025-04-28",
      genres: ["Comedy", "Historical", "Animation"],
      access: "paid",
      status: true,
      description: "",
      video: "",
    },
    {
      id: "war-chronicles",
      name: "War Chronicles",
      type: "tvshow",
      image: "assets/cartazes/series/war_chronicles_poster.png",
      trailer: "https://youtu.be/f6KdMY08WkU?si=xQSRjml8PcX3l_1Z",
      rating: "8",
      language: "Hindi",
      duration: null,
      release: "2025-03-16",
      genres: ["Action", "Comedy", "Horror"],
      access: "free",
      status: true,
      description: "",
      video: "",
    },
    {
      id: "apartment-75-the-midnight-visitor",
      name: "Apartment 75: The Midnight Visitor",
      type: "video",
      image: "assets/cartazes/videos/apartment_75_the_midnight_visitor.png",
      trailer: null,
      rating: null,
      language: "English",
      duration: "01:10",
      release: "",
      genres: [],
      access: "free",
      status: true,
      description: "",
      video: "",
    },
    {
      id: "become-your-best-self",
      name: "Become Your Best Self",
      type: "video",
      image: "assets/cartazes/videos/become_your_best_self.png",
      trailer: null,
      rating: null,
      language: "English",
      duration: "00:50",
      release: "",
      genres: [],
      access: "free",
      status: true,
      description: "",
      video: "",
    },
    {
      id: "genius-home-hacks-for-effortless-living",
      name: "Genius Home Hacks for Effortless Living",
      type: "video",
      image:
        "assets/cartazes/videos/genius_home_hacks_for_effortless_living.png",
      trailer: null,
      rating: null,
      language: "English",
      duration: "01:20",
      release: "",
      genres: [],
      access: "free",
      status: true,
      description: "",
      video: "",
    },
    {
      id: "morning-bliss-routine",
      name: "Morning Bliss Routine",
      type: "video",
      image: "assets/cartazes/videos/morning_bliss_routine.png",
      trailer: null,
      rating: null,
      language: "English",
      duration: "01:50",
      release: "",
      genres: [],
      access: "free",
      status: true,
      description: "",
      video: "",
    },
    {
      id: "beautiful-rangoli-designs",
      name: "Beautiful Rangoli Designs",
      type: "video",
      image: "assets/cartazes/videos/beautiful_rangoli_designs.png",
      trailer: null,
      rating: null,
      language: "English",
      duration: "00:45",
      release: "",
      genres: [],
      access: "free",
      status: true,
      description: "",
      video: "",
    },
    {
      id: "healthy-homemade-diet-plan-effective-weight-loss-at-home",
      name: "Healthy Homemade Diet Plan | Effective Weight Loss at Home",
      type: "video",
      image:
        "assets/cartazes/videos/healthy_homemade_diet_plan_effective_weight_loss_at_home.png",
      trailer: null,
      rating: null,
      language: "English",
      duration: "01:20",
      release: "",
      genres: [],
      access: "free",
      status: true,
      description: "",
      video: "",
    },
    {
      id: "the-power-of-words-this-story-will-change-your-life",
      name: "The Power of Words | This Story Will Change Your Life",
      type: "video",
      image:
        "assets/cartazes/videos/the_power_of_words_this_story_will_change_your_life.png",
      trailer: null,
      rating: null,
      language: "English",
      duration: "00:20",
      release: "",
      genres: [],
      access: "free",
      status: true,
      description: "",
      video: "",
    },
    {
      id: "forever-in-my-heart",
      name: "Forever In My Heart",
      type: "movie",
      image: "assets/cartazes/filmes/forever_in_my_heart_poster.png",
      trailer: "",
      rating: "",
      language: "",
      duration: "",
      release: "",
      genres: [],
      access: "free",
      status: true,
      description: "",
      video: "",
    },
    {
      id: "a-journey-of-triumph",
      name: "A Journey Of Triumph",
      type: "movie",
      image: "assets/cartazes/filmes/a_journey_of_triumph_poster.png",
      trailer: "",
      rating: "",
      language: "",
      duration: "",
      release: "",
      genres: [],
      access: "free",
      status: true,
      description: "",
      video: "",
    },
    {
      id: "beat-box",
      name: "Beat Box",
      type: "movie",
      image: "assets/cartazes/canais/beat_box.png",
      trailer: "",
      rating: "",
      language: "",
      duration: "",
      release: "",
      genres: [],
      access: "free",
      status: true,
      description: "",
      video: "",
    },
    {
      id: "vibe-tv",
      name: "Vibe Tv",
      type: "movie",
      image: "assets/cartazes/canais/vibe_tv.png",
      trailer: "",
      rating: "",
      language: "",
      duration: "",
      release: "",
      genres: [],
      access: "free",
      status: true,
      description: "",
      video: "",
    },
    {
      id: "sports-max",
      name: "Sports Max",
      type: "movie",
      image: "assets/cartazes/canais/sports_max.png",
      trailer: "",
      rating: "",
      language: "",
      duration: "",
      release: "",
      genres: [],
      access: "free",
      status: true,
      description: "",
      video: "",
    },
    {
      id: "znews-247",
      name: "Znews 247",
      type: "movie",
      image: "assets/cartazes/canais/znews_247.png",
      trailer: "",
      rating: "",
      language: "",
      duration: "",
      release: "",
      genres: [],
      access: "free",
      status: true,
      description: "",
      video: "",
    },
    {
      id: "m-tv",
      name: "M Tv",
      type: "movie",
      image: "assets/cartazes/canais/m_tv.png",
      trailer: "",
      rating: "",
      language: "",
      duration: "",
      release: "",
      genres: [],
      access: "free",
      status: true,
      description: "",
      video: "",
    },
    {
      id: "bbp",
      name: "Bbp",
      type: "movie",
      image: "assets/cartazes/canais/bbp.png",
      trailer: "",
      rating: "",
      language: "",
      duration: "",
      release: "",
      genres: [],
      access: "free",
      status: true,
      description: "",
      video: "",
    },
    {
      id: "9xm",
      name: "9Xm",
      type: "movie",
      image: "assets/cartazes/canais/9xm.png",
      trailer: "",
      rating: "",
      language: "",
      duration: "",
      release: "",
      genres: [],
      access: "free",
      status: true,
      description: "",
      video: "",
    },
    {
      id: "dn-tv",
      name: "Dn Tv",
      type: "movie",
      image: "assets/cartazes/canais/dn_tv.png",
      trailer: "",
      rating: "",
      language: "",
      duration: "",
      release: "",
      genres: [],
      access: "free",
      status: true,
      description: "",
      video: "",
    },
    {
      id: "abp-sports",
      name: "Abp Sports",
      type: "movie",
      image: "assets/cartazes/canais/abp_sports.png",
      trailer: "",
      rating: "",
      language: "",
      duration: "",
      release: "",
      genres: [],
      access: "free",
      status: true,
      description: "",
      video: "",
    },
    {
      id: "aaj-kal-live-tv",
      name: "Aaj Kal Live Tv",
      type: "movie",
      image: "assets/cartazes/canais/aaj_kal_live_tv.png",
      trailer: "",
      rating: "",
      language: "",
      duration: "",
      release: "",
      genres: [],
      access: "free",
      status: true,
      description: "",
      video: "",
    },
    {
      id: "victory-vibes",
      name: "Victory Vibes",
      type: "video",
      image: "assets/cartazes/banners/web-home-vibe.jpg",
      trailer: "",
      rating: "",
      language: "English",
      duration: "",
      release: "",
      genres: [],
      access: "free",
      status: true,
      description: "",
      video: "",
    },
    {
      id: "the-daring-player",
      name: "The Daring Player",
      type: "movie",
      image: "assets/cartazes/banners/web-home-player.jpg",
      trailer: "",
      rating: "6.5",
      language: "English",
      duration: "",
      release: "",
      genres: [],
      access: "free",
      status: true,
      description: "",
      video: "",
    },
  ],
  collections: {
    genres: [
      {
        id: "action",
        name: "Action",
        image: "assets/cartazes/generos/action_genre.png",
        status: true,
      },
      {
        id: "animation",
        name: "Animation",
        image: "assets/cartazes/generos/animation_genre.png",
        status: true,
      },
      {
        id: "comedy",
        name: "Comedy",
        image: "assets/cartazes/generos/comedy_genre.png",
        status: true,
      },
      {
        id: "historical",
        name: "Historical",
        image: "assets/cartazes/generos/historical_genre.png",
        status: true,
      },
      {
        id: "horror",
        name: "Horror",
        image: "assets/cartazes/generos/horror_genre.png",
        status: true,
      },
      {
        id: "inspirational",
        name: "Inspirational",
        image: "assets/cartazes/generos/inspirational_genre.png",
        status: true,
      },
      {
        id: "romantic",
        name: "Romantic",
        image: "assets/cartazes/generos/romantic_genre.png",
        status: true,
      },
      {
        id: "thriller",
        name: "Thriller",
        image: "assets/cartazes/generos/thriller_genre.png",
        status: true,
      },
    ],
    languages: [
      {
        id: "english",
        name: "English",
        image: "assets/cartazes/idiomas/English.png",
        status: true,
      },
      {
        id: "hindi",
        name: "Hindi",
        image: "assets/cartazes/idiomas/Hindi.png",
        status: true,
      },
      {
        id: "tamil",
        name: "Tamil",
        image: "assets/cartazes/idiomas/Tamil.png",
        status: true,
      },
      {
        id: "telugu",
        name: "Telugu",
        image: "assets/cartazes/idiomas/Telugu.png",
        status: true,
      },
      {
        id: "malyalam",
        name: "Malyalam",
        image: "assets/cartazes/idiomas/Malyalam.png",
        status: true,
      },
      {
        id: "spanish",
        name: "Spanish",
        image: "assets/cartazes/idiomas/Spanish.png",
        status: true,
      },
      {
        id: "freanch",
        name: "Freanch",
        image: "assets/cartazes/idiomas/Freanch.png",
        status: true,
      },
      {
        id: "arebic",
        name: "Arebic",
        image: "assets/cartazes/idiomas/Arebic.png",
        status: true,
      },
      {
        id: "german",
        name: "German",
        image: "assets/cartazes/idiomas/German.png",
        status: true,
      },
    ],
    actors: [
      {
        id: "michael-johnson",
        name: "Michael Johnson",
        image: "assets/cartazes/elenco/michael_johnson.png",
        status: true,
      },
      {
        id: "james-williams",
        name: "James Williams",
        image: "assets/cartazes/elenco/james_williams.png",
        status: true,
      },
      {
        id: "robert-brown",
        name: "Robert Brown",
        image: "assets/cartazes/elenco/robert_brown.png",
        status: true,
      },
      {
        id: "david-jones",
        name: "David Jones",
        image: "assets/cartazes/elenco/david_jones.png",
        status: true,
      },
      {
        id: "john-miller",
        name: "John Miller",
        image: "assets/cartazes/elenco/john_miller.png",
        status: true,
      },
      {
        id: "daniel-anderson",
        name: "Daniel Anderson",
        image: "assets/cartazes/elenco/daniel_anderson.png",
        status: true,
      },
      {
        id: "matthew-clark",
        name: "Matthew Clark",
        image: "assets/cartazes/elenco/matthew_clark.png",
        status: true,
      },
      {
        id: "andrew-martinez",
        name: "Andrew Martinez",
        image: "assets/cartazes/elenco/andrew_martinez.png",
        status: true,
      },
      {
        id: "joshua-rodriguez",
        name: "Joshua Rodriguez",
        image: "assets/cartazes/elenco/joshua_rodriguez.png",
        status: true,
      },
      {
        id: "christopher-lopez",
        name: "Christopher Lopez",
        image: "assets/cartazes/elenco/christopher_lopez.png",
        status: true,
      },
    ],
    channels: [
      {
        id: "beat-box",
        name: "Beat Box",
        image: "assets/cartazes/canais/beat_box.png",
        status: true,
      },
      {
        id: "vibe-tv",
        name: "Vibe Tv",
        image: "assets/cartazes/canais/vibe_tv.png",
        status: true,
      },
      {
        id: "sports-max",
        name: "Sports Max",
        image: "assets/cartazes/canais/sports_max.png",
        status: true,
      },
      {
        id: "znews-247",
        name: "Znews 247",
        image: "assets/cartazes/canais/znews_247.png",
        status: true,
      },
      {
        id: "m-tv",
        name: "M Tv",
        image: "assets/cartazes/canais/m_tv.png",
        status: true,
      },
      {
        id: "bbp",
        name: "Bbp",
        image: "assets/cartazes/canais/bbp.png",
        status: true,
      },
      {
        id: "9xm",
        name: "9Xm",
        image: "assets/cartazes/canais/9xm.png",
        status: true,
      },
      {
        id: "dn-tv",
        name: "Dn Tv",
        image: "assets/cartazes/canais/dn_tv.png",
        status: true,
      },
      {
        id: "abp-sports",
        name: "Abp Sports",
        image: "assets/cartazes/canais/abp_sports.png",
        status: true,
      },
      {
        id: "aaj-kal-live-tv",
        name: "Aaj Kal Live Tv",
        image: "assets/cartazes/canais/aaj_kal_live_tv.png",
        status: true,
      },
      {
        id: "khabar-now",
        name: "Khabar Now",
        image: "assets/cartazes/canais/khabar_now.png",
        status: true,
      },
      {
        id: "vision-tv",
        name: "Vision Tv",
        image: "assets/cartazes/canais/vision_tv.png",
        status: true,
      },
      {
        id: "headlinex",
        name: "Headlinex",
        image: "assets/cartazes/canais/headlinex.png",
        status: true,
      },
      {
        id: "live-line",
        name: "Live Line",
        image: "assets/cartazes/canais/live_line.png",
        status: true,
      },
      {
        id: "app-live-channel-1",
        name: "App Live Channel 1",
        image: "assets/cartazes/canais/app-live-channel-1.jpg",
        status: true,
      },
      {
        id: "app-live-news",
        name: "App Live News",
        image: "assets/cartazes/canais/app-live-news.jpg",
        status: true,
      },
      {
        id: "goal-tv",
        name: "Goal Tv",
        image: "assets/cartazes/canais/goal_tv.png",
        status: true,
      },
      {
        id: "win-sports",
        name: "Win Sports",
        image: "assets/cartazes/canais/win_sports.png",
        status: true,
      },
      {
        id: "xtreme-sports",
        name: "Xtreme Sports",
        image: "assets/cartazes/canais/xtreme_sports.png",
        status: true,
      },
      {
        id: "pro-play",
        name: "Pro Play",
        image: "assets/cartazes/canais/pro_play.png",
        status: true,
      },
      {
        id: "app-live-wwe",
        name: "App Live Wwe",
        image: "assets/cartazes/canais/app-live-wwe.jpg",
        status: true,
      },
      {
        id: "app-live-soccer",
        name: "App Live Soccer",
        image: "assets/cartazes/canais/app-live-soccer.jpg",
        status: true,
      },
      {
        id: "star-bliss",
        name: "Star Bliss",
        image: "assets/cartazes/canais/star_bliss.png",
        status: true,
      },
      {
        id: "buzz-live",
        name: "Buzz Live",
        image: "assets/cartazes/canais/buzz_live.png",
        status: true,
      },
      {
        id: "fun-box",
        name: "Fun Box",
        image: "assets/cartazes/canais/fun_box.png",
        status: true,
      },
      {
        id: "show-max",
        name: "Show Max",
        image: "assets/cartazes/canais/show_max.png",
        status: true,
      },
      {
        id: "groove-live",
        name: "Groove Live",
        image: "assets/cartazes/canais/groove_live.png",
        status: true,
      },
      {
        id: "tune-in",
        name: "Tune In",
        image: "assets/cartazes/canais/tune_in.png",
        status: true,
      },
      {
        id: "sound-wave",
        name: "Sound Wave",
        image: "assets/cartazes/canais/sound_wave.png",
        status: true,
      },
      {
        id: "rhythmx",
        name: "Rhythmx",
        image: "assets/cartazes/canais/rhythmx.png",
        status: true,
      },
      {
        id: "brain-tv",
        name: "Brain Tv",
        image: "assets/cartazes/canais/brain_tv.png",
        status: true,
      },
      {
        id: "docu-vision",
        name: "Docu Vision",
        image: "assets/cartazes/canais/docu_vision.png",
        status: true,
      },
      {
        id: "discoverx",
        name: "Discoverx",
        image: "assets/cartazes/canais/discoverx.png",
        status: true,
      },
      {
        id: "learn-live",
        name: "Learn Live",
        image: "assets/cartazes/canais/learn_live.png",
        status: true,
      },
      {
        id: "insight-tv",
        name: "Insight Tv",
        image: "assets/cartazes/canais/insight_tv.png",
        status: true,
      },
    ],
  },
  schemas: {
    dashboard: {
      title: "Dashboard",
      columns: [
        "Name",
        "Date",
        "Category",
        "Rating",
        "Name",
        "Date",
        "Plan",
        "Amount",
        "Duration",
        "Payment Method",
      ],
      fields: [],
    },
    "media-library": {
      title: "Media Library",
      columns: ["Name", "Status"],
      fields: [],
    },
    genres: {
      title: "Genres",
      columns: ["Genres", "Status"],
      fields: ["Name", "Status"],
    },
    movies: {
      title: "Movies",
      columns: [
        "Movie",
        "Like",
        "Watch",
        "Access",
        "Plan",
        "Language",
        "Status",
        "Restricted Content",
      ],
      fields: ["Plan"],
    },
    tvshows: {
      title: "TV Shows",
      columns: [
        "TV Show",
        "Like",
        "Watch",
        "Access",
        "Plan",
        "Language",
        "Status",
      ],
      fields: [
        "Plan",
        "Name",
        "TV Show Access",
        "Like",
        "Watch",
        "Language",
        "IMDb Rating",
        "Content Rating",
        "Release Date",
        "Age Restricted",
        "Status",
      ],
    },
    seasons: {
      title: "Seasons",
      columns: ["Season", "TV Show", "Status"],
      fields: ["Name", "TV Show", "Status"],
    },
    episodes: {
      title: "Episodes",
      columns: ["Episode", "TV Show", "Access", "Plan", "Watch", "Status"],
      fields: [
        "Plan",
        "Name",
        "Episode Access",
        "TV Show",
        "Season",
        "IMDb Rating",
        "Content Rating",
        "Duration",
        "Release Date",
        "Age Restricted",
        "Status",
      ],
    },
    videos: {
      title: "Videos",
      columns: [
        "Video",
        "Like",
        "Watch",
        "Access",
        "Plan",
        "Status",
        "Restricted Content",
      ],
      fields: [
        "Plan",
        "Name",
        "Video Access",
        "Duration",
        "Release Date",
        "Like",
        "Watch",
        "Age Restricted",
        "Status",
      ],
    },
    "tv-category": {
      title: "TV Category",
      columns: ["TV Category", "Description", "Status"],
      fields: ["Name", "Description", "Status"],
    },
    "tv-channel": {
      title: "TV Channel",
      columns: ["TV Channel", "TV Category", "Access", "Plan", "Status"],
      fields: [
        "Plan",
        "Name",
        "Stream Type",
        "Embedded",
        "Server URL",
        "Description",
        "Status",
      ],
    },
    "castcrew/actor": {
      title: "Actors",
      columns: ["Actors", "Date Of Birth", "Birth Place", "Status"],
      fields: ["Name", "Birth Place", "Date Of Birth", "Bio"],
    },
    "castcrew/director": {
      title: "Directors",
      columns: ["Directors", "Date Of Birth", "Birth Place", "Status"],
      fields: ["Name", "Birth Place", "Date Of Birth", "Bio"],
    },
    vastads: {
      title: "VAST Ads",
      columns: [
        "Ad Name",
        "Ad Type",
        "Target Type",
        "Start Date",
        "End Date",
        "Status",
      ],
      fields: [
        "Start Date",
        "End Date",
        "Ad Name",
        "Ad Type",
        "Target Type",
        "Target Categories",
        "Status",
      ],
    },
    customads: {
      title: "Custom Ads",
      columns: ["Ad Name", "Placement", "Start Date", "End Date", "Status"],
      fields: ["Start Date", "End Date"],
    },
    subscriptions: {
      title: "Subscriptions",
      columns: [
        "User",
        "Plan",
        "Duration",
        "Payment Method",
        "Start Date",
        "End Date",
        "Total Amount",
        "Status",
      ],
      fields: [
        "User",
        "Plan",
        "Duration",
        "Payment Method",
        "Start Date",
        "End Date",
        "Amount",
        "Discount",
        "Coupon Discount",
        "Tax Amount",
        "Total Amount",
        "Status",
      ],
    },
    plans: {
      title: "Plans",
      columns: [
        "Name",
        "Duration",
        "Level",
        "Price",
        "Discount",
        "Total Price",
        "Status",
      ],
      fields: [
        "Name",
        "Duration",
        "Level",
        "Price",
        "Discount",
        "Total Price",
        "Status",
      ],
    },
    planlimitation: {
      title: "Plan Limits",
      columns: ["Title", "Status"],
      fields: ["Title", "Status"],
    },
    "pay-per-view-history": {
      title: "Rent History",
      columns: [
        "User",
        "Content",
        "Duration",
        "Payment Method",
        "Start Date",
        "End Date",
        "Price",
        "Discount",
        "Total Amount",
      ],
      fields: [
        "User",
        "Content",
        "Duration",
        "Payment Method",
        "Start Date",
        "End Date",
        "Amount",
        "Discount",
        "Total Amount",
      ],
    },
    coupon: {
      title: "Coupon",
      columns: [
        "Coupon Code",
        "Description",
        "Start Date",
        "End Date",
        "Discount Amount",
        "Subscription Plan",
        "Status",
      ],
      fields: [
        "Coupon Code",
        "Description",
        "Start Date",
        "End Date",
        "Discount",
        "Subscription Type",
        "Status",
        "Created At",
        "Updated At",
      ],
    },
    users: {
      title: "Users",
      columns: ["User", "Contact Number", "Gender", "Status"],
      fields: ["First Name", "Last Name", "Email", "Contact Number", "Gender"],
    },
    "soon-to-expire-users": {
      title: "Soon to Expire",
      columns: ["User", "Plan", "End Date", "Status"],
      fields: [],
    },
    reviews: {
      title: "Reviews",
      columns: ["User", "Content", "Rating", "Review", "Date"],
      fields: [],
    },
    banners: {
      title: "App Banner",
      columns: ["Image", "Type", "Type Name", "Title", "Banner For", "Status"],
      fields: ["Type", "Type Name", "Banner For", "Status"],
    },
    constants: {
      title: "Constants",
      columns: ["Name", "Type", "Status"],
      fields: ["Type"],
    },
    "mobile-setting": {
      title: "Mobile Setting",
      columns: ["Name", "Status"],
      fields: [
        "Select Banner",
        "Select Continue Watching",
        "Select Top 10",
        "Select Advertisement",
        "Select New Released Movies",
        "Select Popular language",
        "Select Popular Movies",
        "Select Top Channels",
        "Select Popular Personalities",
        "Select Free Movies",
        "Select Genres",
        "Select Rate our app",
        "Select Popular TV Show",
        "Select Most Watched Videos",
        "Name",
        "Type",
        "Value",
      ],
    },
    notifications: {
      title: "Notification List",
      columns: ["Type", "Text", "User", "Updated At"],
      fields: [],
    },
    "notification-templates": {
      title: "Notification Templates",
      columns: ["Label", "Type", "Status"],
      fields: ["Id", "Label"],
    },
    "setting/general-setting": {
      title: "Business Settings",
      columns: ["Name", "Status"],
      fields: [
        "App",
        "Contact No",
        "Inquiry Email",
        "Site Description",
        "Copyright Text",
        "Facebook URL",
        "X (Twitter) URL",
        "Instagram URL",
        "YouTube URL",
        "Mini Logo",
        "Dark Logo",
        "Favicon",
        "Loader Gif",
      ],
    },
    pages: {
      title: "Pages",
      columns: ["Name", "Status"],
      fields: ["Name"],
    },
    onboardings: {
      title: "Onboarding",
      columns: ["Title", "Description", "Status"],
      fields: ["Title", "Description", "Status"],
    },
    taxes: {
      title: "Tax",
      columns: ["Title", "Type", "Value", "Status"],
      fields: ["Name"],
    },
    faqs: {
      title: "FAQ",
      columns: ["Question", "Answer", "Status"],
      fields: ["Question"],
    },
    "my-profile": {
      title: "Profile",
      columns: ["Name", "Status"],
      fields: [
        "First Name",
        "Last Name",
        "Email",
        "Contact Number",
        "Gender",
        "Male",
        "Female",
        "Other",
      ],
    },
    "setting/custom-code": {
      title: "Custom Code",
      columns: ["Name", "Status"],
      fields: [
        "Custom Css Code (custom_css_block)",
        "Custom Js Code (custom_js_block)",
      ],
    },
    "setting/module-setting": {
      title: "Module Settings",
      columns: ["Name", "Status"],
      fields: [
        "Movies",
        "TV Shows",
        "Live TV",
        "Videos",
        "Import Entertainment Data From TMDB",
        "TMDB API key",
      ],
    },
    "setting/misc-setting": {
      title: "Misc Settings",
      columns: ["Name", "Status"],
      fields: [
        "Google Analytics",
        "Language Option",
        "TimeZone",
        "DataTable Limits",
        "Date Format",
        "Time Format",
        "Forward Seconds",
        "Backward Seconds",
      ],
    },
    "setting/customization": {
      title: "Customization",
      columns: ["Name", "Status"],
      fields: [
        "Primary",
        "Secondary",
        "Glass",
        "Sticky",
        "Transparent",
        "Default",
        "Dark",
        "Color",
        "Mini",
        "Hover",
        "Boxed",
        "Soft",
        "Rounded One Side",
        "Rounded All",
        "Pill One Side",
        "Pill All",
        "Left Bordered",
        "Full Width",
      ],
    },
    "setting/mail": {
      title: "Mail Settings",
      columns: ["Name", "Status"],
      fields: [
        "Email (email)",
        "Mail Driver",
        "Mail Host",
        "Mail Port",
        "Mail Encryption",
        "Mail Username",
        "Password",
        "Mail From",
        "From Name",
      ],
    },
    "setting/notificationsetting": {
      title: "Notification Settings",
      columns: ["Type", "Templates", "Mail", "Mobile"],
      fields: [],
    },
    "setting/language-settings": {
      title: "Language Settings",
      columns: ["Name", "Status"],
      fields: [
        "Language Option",
        "Select File to be translate",
        "Key",
        "Value",
      ],
    },
    "setting/notification-configuration": {
      title: "Notification Configuration",
      columns: ["Name", "Status"],
      fields: ["Expiry Plan", "Upcoming", "Continue Watch"],
    },
    "setting/currency-settings": {
      title: "Currency Settings",
      columns: [
        "Currency Name",
        "Currency Symbol",
        "Currency Code",
        "Is Primary",
      ],
      fields: [
        "Currency Name",
        "Currency Symbol",
        "Currency Code",
        "Is Primary",
        "Currency Position",
        "Thousand Separatorn",
        "Decimal Separator",
        "Number of Decimals",
      ],
    },
    "setting/storage-settings": {
      title: "Storage Settings",
      columns: ["Name", "Status"],
      fields: [
        "Local Storage",
        "S3 Storage",
        "Bunny CDN Storage",
        "AWS Access Key ID",
        "AWS Secret Access Key",
        "AWS Default Region",
        "AWS Bucket",
        "AWS Use Path Style Endpoint",
        "Bunny Storage Zone",
        "Bunny API Key",
        "Bunny CDN URL",
        "Bunny Region",
        "Bunny Stream API Key",
        "Bunny Video Key",
        "Bunny CDN Hostname",
        "Bunny Stream Pull Zone",
      ],
    },
    "setting/seo-settings": {
      title: "SEO Settings",
      columns: ["Name", "Status"],
      fields: [
        "SEO Image",
        "Meta Title",
        "Google Site Verification",
        "Meta Keywords",
        "Global Canonical URL",
        "Site Meta Description",
      ],
    },
  },
  heroes: {
    home: [
      {
        name:"Vingadores Doownsday",
        image: "assets/cartazes/banners/web-home-doomnsday.jpg",
        label: "LANÇAMENTO NO CINEMATCH"
      },
      {
        name:"LANTERNAS",
        image: "assets/cartazes/banners/web-home-lanternas.jpg",
        label: "LANÇAMENTO NO CINEMATCH"
      },
      
      {
        name: "The Daring Player",
        image: "assets/cartazes/banners/web-home-player.jpg",
      },
       {
        name: "Game of Thrones",
        image: "assets/cartazes/banners/web-show-game.jpg",
      },
      
    ],
    movies: [
      {
        name: "Men in black",
        image: "assets/cartazes/banners/web-movie-black.jpg",
      },
      {
        name: "Bluey",
        image: "assets/cartazes/banners/web-home-bluey.jpg",
      },
    ],
    "tv-shows": [
      {
        name: "Fear Factor",
        image: "assets/cartazes/banners/web-show-factor.jpg",
      },     
    ],
    videos: [
      {
        name: "Spiritual Habits for a Calm Mind",
        image: "assets/cartazes/banners/web-videos-mind.jpg",
      },
      {
        name: "Heal Your Mind Before You Fix Your Life",
        image: "assets/cartazes/banners/web-videos-heal.jpg",
      },
    ],
  },
};
